import { Inter } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import ProtectedRoute from './(ProtectedRoute)/ProtectedRoute';
import PostContextProvider from './(context)/postsContext';
import { default as TokenContextProvider } from './(context)/tokenContext';
import UserContextProvider from './(context)/userData';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Articals',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <TokenContextProvider>
          <PostContextProvider>
            <UserContextProvider>
              <ProtectedRoute>
                {children}
                <ToastContainer />
              </ProtectedRoute>
            </UserContextProvider>
          </PostContextProvider>
        </TokenContextProvider>
      </body>
    </html>
  );
}
